
services:
  # Postgres Master (WRITES)
  postgres-master:
    image: bitnami/postgresql:latest
    container_name: postgres-master
    environment:
      - POSTGRESQL_USERNAME=open_space
      - POSTGRESQL_PASSWORD=open_space
      - POSTGRESQL_DATABASE=open_space
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_master_data:/bitnami/postgresql

  # Postgres Replica (READS)
  postgres-replica:
    image: bitnami/postgresql:latest
    container_name: postgres-replica
    environment:
      - POSTGRESQL_USERNAME=open_space
      - POSTGRESQL_PASSWORD=open_space
      - POSTGRESQL_DATABASE=open_space
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_MASTER_HOST=postgres-master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
    ports:
      - "5433:5432"
    depends_on:
      - postgres-master

  # pgAdmin (Postgres GUI)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: open_space_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres-master

  # Redis Cluster Node 0 (Master 1)
  redis-node-0:
    image: bitnami/redis-cluster:latest
    container_name: redis-node-0
    environment:
      - REDIS_PASSWORD=open_space_redis
      - REDIS_NODES=redis-node-0 redis-node-1 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5
    ports:
      - "6379:6379"

  # Redis Cluster Node 1 (Master 2)
  redis-node-1:
    image: bitnami/redis-cluster:latest
    container_name: redis-node-1
    environment:
      - REDIS_PASSWORD=open_space_redis
      - REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5

  # Redis Cluster Node 2 (Master 3)
  redis-node-2:
    image: bitnami/redis-cluster:latest
    container_name: redis-node-2
    environment:
      - REDIS_PASSWORD=open_space_redis
      - REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5

  # Redis Cluster Node 3 (Slave 1)
  redis-node-3:
    image: bitnami/redis-cluster:latest
    container_name: redis-node-3
    environment:
      - REDIS_PASSWORD=open_space_redis
      - REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5

  # Redis Cluster Node 4 (Slave 2)
  redis-node-4:
    image: bitnami/redis-cluster:latest
    container_name: redis-node-4
    environment:
      - REDIS_PASSWORD=open_space_redis
      - REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5

  # Redis Cluster Node 5 (Slave 3)
  redis-node-5:
    image: bitnami/redis-cluster:latest
    container_name: redis-node-5
    environment:
      - REDIS_PASSWORD=open_space_redis
      - REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5

  # Redis Insight (Management UI)
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: open_space_redisinsight
    ports:
      - "5540:5540"
    depends_on:
      - redis-node-0

  # RabbitMQ Management
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: open_space_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672" # RabbitMQ connection port
      - "15672:15672" # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq


volumes:
  postgres_master_data:
  rabbitmq_data:
