packages:
  - apps/*
  - libs/*

ignoredBuiltDependencies:
  - "@nestjs/core"
  - "@prisma/client"
  - "@prisma/engines"
  - "@swc/core"
  - bcrypt
  - core-js
  - core-js-pure
  - msgpackr-extract
  - nx
  - prisma
  - unrs-resolver
